# Generated by Django 5.2.17 on 2026-08-09 08:12

import django.db.models.deletion
import django.utils.timezone
import reconciliation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=reconciliation.models.image_upload_path)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to=reconciliation.models.excel_upload_path)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('analyzed', 'تمت المطابقة'), ('error', 'حدث خطأ')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تسوية يومية',
                'verbose_name_plural': 'التسويات اليومية',
                'ordering': ['-date', 'pharmacy__name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صيدلية',
                'verbose_name_plural': 'الصيدليات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differences', models.JSONField(blank=True, default=list)),
                ('matched_rows_count', models.PositiveIntegerField(default=0)),
                ('mismatched_rows_count', models.PositiveIntegerField(default=0)),
                ('missing_in_image', models.JSONField(blank=True, default=list)),
                ('missing_in_excel', models.JSONField(blank=True, default=list)),
                ('totals_diff', models.JSONField(blank=True, default=dict)),
                ('summary_ar', models.TextField(blank=True, default='')),
                ('raw_image_extraction', models.JSONField(blank=True, default=dict)),
                ('raw_excel_table', models.JSONField(blank=True, default=dict)),
                ('converted_excel_file', models.FileField(blank=True, null=True, upload_to=reconciliation.models.converted_excel_upload_path)),
                ('has_differences', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciliation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_result', to='reconciliation.dailyreconciliation')),
            ],
            options={
                'verbose_name': 'نتيجة مطابقة',
                'verbose_name_plural': 'نتائج المطابقة',
            },
        ),
        migrations.AddField(
            model_name='dailyreconciliation',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='reconciliation.pharmacy'),
        ),
        migrations.AddConstraint(
            model_name='dailyreconciliation',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'date'), name='unique_pharmacy_per_day'),
        ),
    ]
