# Generated by Django 5.2.17 on 2026-08-10 12:30

import reconciliation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_seed_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreconciliation',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to=reconciliation.models.image_upload_path),
        ),
    ]
